# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_solver <- function(args) {
    .Call(`_balnet_rcpp_solver`, args)
}

rcpp_col_stats <- function(X, weights, compute_sd, n_threads) {
    .Call(`_balnet_rcpp_col_stats`, X, weights, compute_sd, n_threads)
}

rcpp_sp_tcrossprod_plus <- function(X, beta, intercepts, n_threads) {
    .Call(`_balnet_rcpp_sp_tcrossprod_plus`, X, beta, intercepts, n_threads)
}

rcpp_standardize <- function(X, center, scale, n_threads) {
    .Call(`_balnet_rcpp_standardize`, X, center, scale, n_threads)
}

rcpp_standardize_inplace <- function(X, center, scale, n_threads) {
    invisible(.Call(`_balnet_rcpp_standardize_inplace`, X, center, scale, n_threads))
}

