// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_solver
Rcpp::List rcpp_solver(const Rcpp::List args);
RcppExport SEXP _balnet_rcpp_solver(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_solver(args));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_col_stats
Rcpp::List rcpp_col_stats(const Rcpp::NumericMatrix& X, const Rcpp::NumericMatrix& weights, bool compute_sd, size_t n_threads);
RcppExport SEXP _balnet_rcpp_col_stats(SEXP XSEXP, SEXP weightsSEXP, SEXP compute_sdSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< bool >::type compute_sd(compute_sdSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_col_stats(X, weights, compute_sd, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_sp_tcrossprod_plus
Rcpp::NumericMatrix rcpp_sp_tcrossprod_plus(const Rcpp::NumericMatrix& X, const Eigen::SparseMatrix<double, Eigen::RowMajor>& beta, const Rcpp::NumericVector& intercepts, size_t n_threads);
RcppExport SEXP _balnet_rcpp_sp_tcrossprod_plus(SEXP XSEXP, SEXP betaSEXP, SEXP interceptsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double, Eigen::RowMajor>& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_sp_tcrossprod_plus(X, beta, intercepts, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_standardize
Rcpp::NumericMatrix rcpp_standardize(const Rcpp::NumericMatrix& X, const Rcpp::NumericVector& center, const Rcpp::NumericVector& scale, size_t n_threads);
RcppExport SEXP _balnet_rcpp_standardize(SEXP XSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_standardize(X, center, scale, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_standardize_inplace
void rcpp_standardize_inplace(Rcpp::NumericMatrix& X, const Rcpp::NumericVector& center, const Rcpp::NumericVector& scale, size_t n_threads);
RcppExport SEXP _balnet_rcpp_standardize_inplace(SEXP XSEXP, SEXP centerSEXP, SEXP scaleSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< size_t >::type n_threads(n_threadsSEXP);
    rcpp_standardize_inplace(X, center, scale, n_threads);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_balnet_rcpp_solver", (DL_FUNC) &_balnet_rcpp_solver, 1},
    {"_balnet_rcpp_col_stats", (DL_FUNC) &_balnet_rcpp_col_stats, 4},
    {"_balnet_rcpp_sp_tcrossprod_plus", (DL_FUNC) &_balnet_rcpp_sp_tcrossprod_plus, 4},
    {"_balnet_rcpp_standardize", (DL_FUNC) &_balnet_rcpp_standardize, 4},
    {"_balnet_rcpp_standardize_inplace", (DL_FUNC) &_balnet_rcpp_standardize_inplace, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_balnet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
